# Generated by Django 2.1 on 2020-01-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('prod_id', models.CharField(max_length=100)),
                ('device_sl', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('device_bcode', models.CharField(max_length=100)),
                ('device_date', models.DateField()),
                ('device_hsn', models.IntegerField()),
            ],
        ),
    ]
