# Generated by Django 2.1 on 2020-01-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_hsn',
            field=models.IntegerField(max_length=100),
        ),
    ]
