# Generated by Django 2.1 on 2020-01-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200113_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_hsn',
            field=models.CharField(max_length=100),
        ),
    ]
