# Generated by Django 2.1 on 2020-01-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200113_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_hsn',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
