# Generated by Django 2.1 on 2020-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20200113_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_date',
            field=models.CharField(max_length=100),
        ),
    ]
