# Generated by Django 2.1 on 2020-01-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20200114_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_date',
            field=models.DateField(),
        ),
    ]
