# Generated by Django 2.1 on 2020-01-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20200115_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_date',
            field=models.CharField(max_length=100),
        ),
    ]
