# Generated by Django 2.1 on 2020-01-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
