# Generated by Django 2.1 on 2020-01-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0002_auto_20200109_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_signup',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
