# Generated by Django 2.1 on 2019-12-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeritems',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
