# Generated by Django 2.1 on 2020-01-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createitems',
            fields=[
                ('prod_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('cprod_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
